using Sox.Core.SearchIndex;
namespace Sox.Core.IndexV2.Alias;

// Detects that a just-opened snapshot's baked-in alias data was generated by a different set of alias
// providers (installed/removed, or one bumped its own Version) than what's installed right now, and
// kicks off a background forced recompaction to regenerate it -- see AliasProviderRegistry.
// ComputeProvidersFingerprint and AliasGeneration for why this is the only thing that can make
// existing aliases stale (enabled/disabled toggling never does, so it never triggers this).
internal static class AliasProvidersReconciler
{
    public static void ReconcileIfStale(LiveIndex live, string path, string drive)
    {
        var stored = live.Read((snapshot, _) => snapshot.AliasProvidersFingerprint);
        var current = AliasProviderRegistry.ComputeProvidersFingerprint();
        if (stored == current)
            return;

        // Fire-and-forget: Compact() already holds its own write lock for the duration (searches against
        // this drive block for one recompaction, same as any other idle-triggered compaction), and this
        // is a rare event (only an alias plugin install/removal/version bump triggers it, all of which
        // require an app/service restart) -- not worth making the caller (snapshot open) wait on it.
        _ = Task.Run(() =>
        {
            try
            {
                if (live.Compact(path, force: true))
                    Logger.Log($"[AliasProvidersReconciler] {drive}: alias providers changed since last write, aliases regenerated.");
            }
            catch (Exception ex)
            {
                Logger.Log($"[AliasProvidersReconciler] {drive}: failed to regenerate aliases: {ex.Message}", LogLevel.Error);
            }
        });
    }
}
