<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Sox.Plugins.FileDialog</AssemblyName>
    <Version>1.0.0</Version>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sox.PluginSdk\PluginSdk.csproj" Private="false" />
  </ItemGroup>
</Project>
