<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Sox.Plugins.FileDialog</AssemblyName>
    <Version>1.0.0</Version>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sox.PluginSdk\PluginSdk.csproj" Private="false" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetDir)$(TargetName).dll" DestinationFolder="..\..\Sox.App\bin\$(Configuration)\net10.0-windows\Plugins\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).dll" DestinationFolder="..\..\Sox.Service\bin\$(Configuration)\net10.0-windows\Plugins\" SkipUnchangedFiles="true" />
  </Target>
</Project>
