<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Sox.Plugins.PinyinAlias</AssemblyName>
    <Version>1.1.7</Version>
      <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sox.PluginSdk\PluginSdk.csproj" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sox.Plugins.PinyinAlias.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Translations\**\*.json" />
    <EmbeddedResource Include="Resources\pinyin.bin" />
  </ItemGroup>
</Project>
